Controllers/AdminTransactionController.cs
using FinallLaibrary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FinallLaibrary.Controllers
{
   // [Authorize]
    public class AdminTransactionController : Controller
    {
        private LaibraryManagementEntities transDb = new LaibraryManagementEntities();
        private LaibraryManagementEntities bookDb = new LaibraryManagementEntities();
        public ActionResult Requests()
        {
            return View(transDb.tblTransactions.ToList());
        }
        public ActionResult GetAllRequests()
        {
            var transactionList = transDb.tblTransactions.Where(r => r.TranStatus == "Requested").ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult AcceptRequest(int? tranId)
        {
            if (tranId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            tblTransaction transaction = transDb.tblTransactions.FirstOrDefault(t => t.TranId == tranId);
            if (transaction == null)
            {
                return HttpNotFound();
            }

            transaction.TranStatus = "Accepted";
            transaction.TranDate = DateTime.Now.ToShortDateString();
            transDb.SaveChanges();

            return RedirectToAction("Requests");
        }
        public ActionResult Return()
        {
            return View(transDb.tblTransactions.ToList());
        }
        // Returns all return books in json format.
        public ActionResult GetAllReturn()
        {
            var transactionList = transDb.tblTransactions.Where(r => r.TranStatus == "Returned").ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult AcceptReturn(int? tranId)
        {
            if (tranId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTransaction transaction = transDb.tblTransactions.FirstOrDefault(t => t.TranId == tranId);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            tblBook book = bookDb.tblBooks.FirstOrDefault(b => b.BookId == transaction.BookId);
            book.BookCopies = book.BookCopies + 1;
            bookDb.SaveChanges();
            transDb.tblTransactions.Remove(transaction);
            transDb.SaveChanges();
            return View("Return");

        }
    }
}

Views/AdminTransaction/Requests.cshtml
@model IEnumerable<FinallLaibrary.Models.tblTransaction>

@{
    ViewBag.Title = "Requests";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Request list</h4>
<hr />

<link rel="stylesheet" , href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link rel="stylesheet" , href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />
<table width="100%" class="table table-hover table-bordered" id="example">
    <thead class="bg-success text-light">
        <tr>
            <th>
                Book Title
            </th>
            <th>
                Book ISBN
            </th>
            <th>
                Request Date
            </th>
            <th>
                User Name
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                BookTitle
            </th>
            <th>
                BookISBN
            </th>
            <th>
                TranDate
            </th>
            <th>
                UserName
            </th>
        </tr>
    </tbody>
</table>
<br />


@section scripts{
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                "ajax": {
                    "url": "/AdminTransaction/GetAllRequests",
                    "type": "get",
                    "datatype": "json",
                },
                "columns": [
                    { "data": "BookTitle" },
                    { "data": "BookISBN" },
                    { "data": "TranDate" },
                    { "data": "UserName" },
                    {
                        "data": "TranId", "render": function (idhere) {

                            return " <a onclick='acceptRequest()' class='btn btn-sm btn-primary text-light' data-toggle='tooltip' title='Accept book request' href='@Url.Action("AcceptRequest", "AdminTransaction")?tranId=" + idhere + "'> <i class='fas fa-check-circle'></i> Accept</a>";
                        },
                        "orderable": false,
                        "width": "160px"
                    }
                ],
                "language": {
                    "emptyTable": "No data found, Wait for the users to take action."
                }
            });
        });

        function acceptRequest(){
                alert("Book request accepted successfully")
        };

      
    </script>
}

Views/AdminTransaction/Return.cshtml
@model IEnumerable<FinallLaibrary.Models.tblTransaction>

@{
    ViewBag.Title = "Return";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Return list</h4>
<hr />

@*External stylesheet for data table plugins*@
<link rel="stylesheet" , href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link rel="stylesheet" , href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />
<table width="100%" class="table table-hover table-bordered" id="example">
    <thead class="bg-success text-light">
        <tr>
            <th>
                Book Title
            </th>
            <th>
                Book ISBN
            </th>
            <th>
                Return Date
            </th>
            <th>
                User Name
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                BookTitle
            </th>
            <th>
                BookISBN
            </th>
            <th>
                TranDate
            </th>
            <th>
                UserName
            </th>
        </tr>
    </tbody>
</table>
<br />

@*Java scripts*@
@section scripts{
    @*External scripts for data table plugins*@
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script>
        @*Data table plugin*@
        $(document).ready(function () {
            $('#example').DataTable({
                "ajax": {
                    "url": "/AdminTransaction/GetAllReturn",
                    "type": "get",
                    "datatype": "json",
                },
                "columns": [
                    { "data": "BookTitle" },
                    { "data": "BookISBN" },
                    { "data": "TranDate" },
                    { "data": "UserName" },
                    {
                        "data": "TranId", "render": function (idhere) {

                            return " <a onclick='acceptReturn()' class='btn btn-sm btn-primary text-light' data-toggle='tooltip' title='Accept return request' href='@Url.Action("AcceptReturn", "AdminTransaction")?tranId=" + idhere + "'> <i class='fas fa-check-circle'></i> Accept</a> ";
                        },
                        "orderable": false,
                        "width": "60px"
                    }
                ],
                "language": {
                    "emptyTable": "No data found, Wait for the users to take action."
                }
            });
        });
        @*Scripts for accept alert*@
        function acceptReturn(){
                alert("Return request accepted successfully")
        };
    </script>
}